[alias]
ci-check = "check --release --workspace --all-targets --all-features --locked"
ci-clippy = "clippy --release --workspace --all-targets --all-features --locked -- -D warnings"
ci-doc = "doc --release --workspace --no-deps --all-features --locked"
