name: Format

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: Check formatting
        run: ./scripts/format.sh --check
